# services:
#   app:
#     image: blog:latest
#     ports:
#       - "80:80"
#     volumes:
#       - ~/dev/github/jdev9487/blog/default.conf:/etc/nginx/conf.d/default.conf:ro

version: '3.8'
services:
  blog-app:
    # image: blog # Placeholder for pushing image to Dockerhub
    build:
      context: .
      dockerfile: Dockerfile
  nginx:
    # image: csrinu236/medium-nginx-app # Placeholder for pushing image to Dockerhub
    build:
      context: ./.nginx
      dockerfile: Dockerfile
    depends_on:
      - blog-app
    ports:
      - '8080:8080'
    environment:
      - NEXTJS_CONTAINER_IP=blog-app # supplying environment vars for convert-nginx.sh file.
    command: [ 'sh', '/etc/nginx/convert-nginx.sh'] 