version: '3.8'
services:
  blog-app:
    image: jdev9487/blog:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
  nginx:
    image: jdev9487/blog-proxy-server:latest
    # build:
    #   context: ./.nginx
    #   dockerfile: Dockerfile
    depends_on:
      - blog-app
    ports:
      - '443:443'
      - '80:80'
    volumes:
      - ./.nginx/default.conf:/etc/nginx/conf.d/default.conf:ro