name: Build and Push to DockerHub

on: 
  push:
    tags:
    - '*'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push next js
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog:latest
      -
        name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./.nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-proxy-server:latest
