name: Build and Push to DockerHub

on: 
  push:
    tags:
    - '*'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Download markdown
        uses: robinraju/release-downloader@v1.9
        with:
          repository: jdev9487/blog-markdown
          latest: true
          filename: "*.md"
          out-file-path: "markdown"
      -
        name: Delete dummy blogs
        run: rm -rf ./content/blog/
      -
        name: Move artifacts
        run: sh .github/scripts/copy-markdown-files.sh
      -
        name: Download animations
        uses: robinraju/release-downloader@v1.9
        with:
          repository: jdev9487/math-blog-animations
          latest: true
          filename: "*.mp4"
          out-file-path: "animations"
      -
        name: Copy animations
        run: sh .github/scripts/copy-animations.sh
      -
        name: LIIIIIIIIIIIIST
        run: ls -R && cat ./content/blog/quadratic-formula/index.md
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog:latest
