name: Build and Push to DockerHub

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout markdown repo
        uses: actions/checkout@v4
        with:
          repository: jdev9487/blog-markdown
          token: ${{ secrets.MARKDOWN_PAT }}
          path: ./blog-markdown
      -
        name: Create artifact
        uses: actions/upload-artifact@v4
        with:
          name: blog-markdowns
          path: ./blog-markdown
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: blog-markdowns
          path: ./artifacts
      -
        name: Delete dummy blogs
        run: rm -rf ./content/blog/
      -
        name: Move artifacts
        run: sh ./github/scripts/copy-markdown-files.sh
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog:latest