name: Build and Push to DockerHub

on: 
  push:
    tags:
    - '*'


jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Download markdown
        uses: robinraju/release-downloader@v1.9
        with:
          repository: jdev9487/blog-markdown
          latest: true
          filename: "*.md"
          out-file-path: "markdown"
      -
        name: Delete dummy blogs
        run: rm ./src/posts/*
      -
        name: Copy markdown
        run: sh .github/scripts/copy-markdown-files.sh
      -
        name: Delete dummy avatars
        run: rm ./public/avatars/*
      -
        name: Fetch user avatars
        run: sh .github/scripts/fetch-user-avatars.sh
      -
        name: Download animations
        uses: robinraju/release-downloader@v1.9
        with:
          repository: jdev9487/math-blog-animations
          latest: true
          filename: "*"
          out-file-path: "animations"
      -
        name: Delete dummy animations
        run: rm ./public/animations/*
      -
        name: Copy animations
        run: sh .github/scripts/copy-animations.sh
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push next js
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog:latest
      -
        name: Build and push nginx
        uses: docker/build-push-action@v5
        with:
          context: ./.nginx
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blog-proxy-server:latest
